[package]
name = "mahjong"
version = "0.1.0"
authors = ["Malik Olivier Boussejra <malik@boussejra.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"